version: "3.9"
services:
    app:
        build: 
            context: "./src"
            args:
                APP_BASEPATH: "/overlay/"
        ports:
            - "8888:5000"
        environment: 
            PORT: "5000"
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: p4ssword
        volumes: 
            - postgres-data:/var/lib/postgresql/data
volumes: 
    postgres-data: